#ifndef TASKS_COMMON_H_
#define TASKS_COMMON_H_

#define UART_READ_TASK_STACK_SIZE 4096
#define UART_READ_TASK_PRIORITY   5
#define UART_READ_TASK_CORE_ID    0

#define UART_CMD_TASK_STACK_SIZE 4096
#define UART_CMD_TASK_PRIORITY   5
#define UART_CMD_TASK_CORE_ID    0

#define DISPLAY_CONTROL_TASK_STACK_SIZE 4096
#define DISPLAY_CONTROL_TASK_PRIORITY   5
#define DISPLAY_CONTROL_TASK_CORE_ID    1

#define DISPLAY_RUN_TASK_STACK_SIZE 4096
#define DISPLAY_RUN_TASK_PRIORITY   5
#define DISPLAY_RUN_TASK_CORE_ID    1

#define DISPLAY_TICKER_TASK_STACK_SIZE    4096
#define DISPLAY_TICKER_READ_TASK_PRIORITY 5
#define DISPLAY_TICKER_READ_TASK_CORE_ID  1

#endif